stages:
- stage: Dev1
  dependsOn:
  - Sandbox
  condition: succeeded('Sandbox')
  jobs:
  - deployment: Dev1
    displayName: Dev1
    pool:
      vmImage: windows-latest
    environment:
      name: Dev1
    strategy:
      runOnce:
        deploy:
          steps:
          - template: include-steps.yml
            parameters:
              stepName: 'Dev1'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                throw "simulate a failure"
                
- stage: Dev2
  dependsOn:
  - Sandbox
  condition: succeeded('Sandbox')
  jobs:
  - deployment: Dev2
    displayName: Dev2
    pool:
      vmImage: windows-latest
    environment:
      name: Dev2
    strategy:
      runOnce:
        deploy:
          steps:
          - template: include-steps.yml
            parameters:
              stepName: 'Dev2'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                write-host ***************************
                write-host 'Dev2'
                write-host ***************************
