stages:
- stage: Build
  pool:
    vmImage: windows-latest
  jobs:
  - job: Build
    displayName: 'Build FAN5'
    workspace:
      clean: all
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          write-host ***************************
          write-host 'Build'
          write-host ***************************
- stage: Sandbox
  dependsOn:
  - Build
  condition: succeeded('Build')
  jobs:
  - deployment: Sandbox
    displayName: Sandbox
    pool:
      vmImage: windows-latest
    environment:
      name: Sandbox
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                write-host ***************************
                write-host 'Sandbox'
                write-host ***************************
- stage: Dev1
  dependsOn:
  - Sandbox
  condition: succeeded('Sandbox')
  jobs:
  - deployment: Dev1
    displayName: Dev1
    pool:
      vmImage: windows-latest
    environment:
      name: Dev1
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                write-host ***************************
                write-host 'Dev1'
                write-host ***************************
- stage: Dev2
  dependsOn:
  - Sandbox
  condition: succeeded('Sandbox')
  jobs:
  - deployment: Dev2
    displayName: Dev2
    pool:
      vmImage: windows-latest
    environment:
      name: Dev1
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                write-host ***************************
                write-host 'Dev2'
                write-host ***************************
- stage: QE
  dependsOn: []
  condition: or(succeeded('Dev1'), succeeded('Dev2')  )
  jobs:
  - deployment: QE
    displayName: QE
    pool:
      vmImage: windows-latest
    environment:
      name: QE
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                write-host ***************************
                write-host 'QE'
                write-host ***************************
- stage: PE
  dependsOn:
  - QE
  condition: succeeded('QE')
  jobs:
  - deployment: PE
    displayName: PE
    pool:
      vmImage: windows-latest
    environment:
      name: PE
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |-
                write-host ***************************
                write-host 'PE'
                write-host ***************************
