trigger:
  branches:
    include:
    - main
  paths:
    include:
    - .pipelines/nested-env-demo.yml
    
stages:
- stage: Build
  pool:
    vmImage: windows-latest
  jobs:
  - template: templates/sample-job-reuse.yml
    parameters:
      jobName: 'Build'
        
- stage: Sandbox
  dependsOn:
  - Build
  condition: succeeded('Build')
  jobs:
  - deployment: Sandbox
    displayName: Sandbox
    pool:
      vmImage: windows-latest
    environment:
      name: Sandbox
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/include-steps.yml
            parameters:
              stepName: 'Sandbox'

- template: ./templates/dev-template.yml
  
- stage: QE
  jobs:
  - deployment: QE
    displayName: QE
    pool:
      vmImage: windows-latest
    environment:
      name: QE
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/include-steps.yml
            parameters:
              stepName: 'QE'
          
- stage: PE
  dependsOn:
  - QE
  condition: succeeded('QE')
  jobs:
  - deployment: PE
    displayName: PE
    pool:
      vmImage: windows-latest
    environment:
      name: PE
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/include-steps.yml
            parameters:
              stepName: 'PE'
